### ISSUE TITLE
Some general questions

### ISSUE THREAD

**Issue by liorphp** [batdan/midjourney-api-php#4]
1. Is it possible to get the image status on Callback url? (0%, 10%, 90%...)
2. Is it possible to generate image using the "relax" mode?

Thanks!

**Comment by batdan** [comment]
Hi Lior Chamla,

**1. Is it possible to get the image status on Callback url? (0%, 10%, 90%...)**

The methods responsible for retrieving the proposal of 4 images and the one retrieving the final image perform a search for the object created from data from the midjourney prompt.

To avoid disturbing the Midjourney prompt which is very sensitive, I passed a sort of unique id (based on timestamp) in the seed tag which normally serves to maintain visual continuity in a project.

So it's only when the 4 images or the final image are created that the search via the discord API return an answer.

I don't have a solution for the moment to have a progression of the creation.

**Is it possible to generate image using the "relax" mode?**

If I understood the question correctly, we are talking about features related to the midjourney prompt.

This package skips all the features offered by Midjourney, except for the seed tag that I used to retrieve the images.

I saw another similar script that searched the entire prompt for an image.

The problem was that if we offered an image with a url in a prompt to inspire midjourney, nothing worked anymore because the image link is then replaced by midjourney and the prompt therefore becomes different from the one we sent. No longer possible to recover the image.

There I think that no functionality is missing.

I suggest you study the midjourney tags. We are in a logic far removed from a GPT prompt.

For my part, I automated the creation of prompt midjourney with a prompt GPT. But it was not a simple affair, it was necessary to be very directive.

PS: don't forget the little star if you like the package ;)

**Comment by liorphp** [comment]
2.
Can I just use the --seed parameter?

What about these parameters:
--v
--q
-stylize
--relax

**Comment by batdan** [comment]
Currently all tags are available except "seed"

I will be able to see later if I go out of this logic by checking that this has no impact on the images generated

**Comment by liorphp** [comment]
Thanks!
"discordUserToken" is permanent? or does it change and I have to check him value every time?

**Comment by liorphp** [comment]
Great, thanks!

**Comment by batdan** [comment]
In the v2.1.2 release, I added a new "imageCreationV2" method that separates the textual part of a prompt and the tags.

By using it, there are no more limitations with Midjourney prompts and the "seed" tag is now available.

I kept the "imageCreation" method to ensure backwards compatibility for projects that use it.

Example of the new implementation:

```php
$midjourney = new MidjourneyImageCreator($discordChannelId, $discordUserToken);

// Example of a prompt: text is separated from tags
$promptText = "aerial view of a giant fish tank shaped like a tower in the middle of new york city, https://depuismonhamac.jardiland.com/wp-content/uploads/2019/06/AdobeStock_196378179.jpeg";
$promptTags = "8k octane render, photorealistic --ar 9:20 --v 5";

// The process of generating and upscaling an image typically takes approximately one minute.
$message = $midjourney->imageCreationV2($promptText, $promptTags);
$imgUrl  = $message->upscaled_photo_url;
```
